### ISSUE TITLE
Не открывается веб-интерфейс после получения токена

### ISSUE THREAD

**Issue by dronix27** [ad/domru#14]
Запускаю аддон первый раз. Получаю токен. Перезапускаю. Аддон запускается, но веб-страница не открывается: Ошибка 502: Bad Gateway.
Фрагмент журнала:
2024/05/13 04:38:04 http: panic serving 172.30.32.2:34690: runtime error: index out of range [0] with length 0
goroutine 41 [running]:
net/http.(*conn).serve.func1()
/usr/local/go/src/net/http/server.go:1898 +0xbe
panic({0x853b80?, 0xc0000cc198?})
/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/ad/domru/handlers.(*Handler).HANetwork(0x847640?)
/go/src/app/handlers/api.go:75 +0x850
github.com/ad/domru/handlers.(*Handler).HomeHandler(0xc0000b04c0, {0x932958, 0xc0001bc000}, 0xc0000ced80)

**Comment by dronix27** [comment]
Проверил на виртуалке - всё работает. Значит, дело не аддоне.
